//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilePath
    {
        public int FilePathId { get; set; }
        public string FileName { get; set; }
        public int FileType { get; set; }
        public int ProductId { get; set; }
        public string ContentType { get; set; }
        public byte[] Content { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
